services:
  db:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    env_file:
      - .db.env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dci

  platform:
    image: localhost/platform:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9080:9080
    depends_on:
      - db
    networks:
      - dci
    env_file:
      - .server.env

networks:
  dci:
    external: true

volumes:
  data: